sudo: false
language: php
matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7
  - php: hhvm
  allow_failures:
  - php: 7
  - php: hhvm
cache:
  directories:
  - "$HOME/.composer/cache"
before_script:
- composer self-update
- composer config --global github-oauth.github.com ${GH_TOKEN}
- composer install
script:
- vendor/bin/phpunit
after_script:
- vendor/bin/coveralls -v
notifications:
  email: false
env:
  global:
    secure: JouyXSafksQxzb/garjRvei5QyttudOxylZAxVVfT0ckdd48Q6ffMKe4j8L6TDYzxlNVoCu/b+h5lHmrcwfaU+ogrv3qqpd2kHAzvvHiPj7/m27aj/d5xAf4uDZaxS0Deuqf0Qs214UiTPoyGLLPYydHcGQSGU443Ju8BQxpl3U=
