language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

services:
    - mongodb
    - mysql

before_script:
    - composer self-update
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -e "create database squeue;"
    - mysql --database=squeue < library/Adapter/Db/mysql.sql
    - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php
    - composer install --dev --prefer-source
    - mkdir -p build/coverage

script:
    - vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v

notifications:
    email: false
