language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

services:
    - mongodb
    - mysql

before_script:
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -e "create database zfqueue;"
    - mysql --database=zfqueue < library/ZendQueue/Adapter/Db/mysql.sql
    - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php
    - composer selfupdate
    - composer install --dev --prefer-source
    - cd tests

script:
    - ../vendor/bin/phpunit --coverage-clover=../build/coverage.clover

after_script:
    - cd ..
    - php vendor/bin/coveralls -v

notifications:
    email: false
